apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal-agent.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "temporal-agent.labels" . | nindent 4 }}
